import type { Metadata } from "next";
import "./globals.css";
import { cookies } from "next/headers";
import { getFontFamilyClassName } from "~lib/fonts";
import { cn } from "~lib/utils";
import StoreSetter from "~lib/theme/components/store-setter";
import { AppTheme } from "~lib/theme/constants";
import { CommandPallette } from "~modules/common/components/command-pallette";
import { CreateTaskDrawerWrapper } from "~modules/tasks/layouts/create-task-drawer-wrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const theme: AppTheme =
    (cookies().get("__theme__")?.value as AppTheme) ?? AppTheme.DARK;

  return (
    <html lang="en" data-theme={theme}>
      <body
        className={cn(
          getFontFamilyClassName("inter"),
          "bg-bodySecondary text-text100",
        )}>
        {children}
        <StoreSetter theme={theme} />
        <CommandPallette />
        <CreateTaskDrawerWrapper />
      </body>
    </html>
  );
}
