import type { Metadata } from "next";
import "./globals.css";
import {getFontFamilyClassName} from "~lib/fonts";
import {cn} from "~lib/utils";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(getFontFamilyClassName("inter"), "bg-red-50")}>{children}</body>
    </html>
  );
}
